import './src/components/chat_bubble.ts';
import './src/components/document_preview.ts';
import {parseDocumentFile} from './src/services/document_service.ts';
import {validateCitations} from './src/services/citation_service.ts';
const response = await fetch('/examples/bitcoin.pdf');
const documentFile = await parseDocumentFile(new File([await response.blob()], 'bitcoin.pdf', {type:'application/pdf'}));
const source = documentFile.blocks.find(block => block.text.includes('a new key pair should be used'))!;
const other = documentFile.blocks.find(block => block.page === 6 && block.id !== source.id && block.text.length > 200)!;
const question = document.querySelector('document-chat-bubble#question')! as any;
const answer = document.querySelector('document-chat-bubble#answer')! as any;
const viewer = document.querySelector('document-preview')! as any;
viewer.document = documentFile;
const text = `A new key pair helps prevent transactions from being linked to a common owner [[${source.id}]].\n\nThe paper discusses this in its privacy section [${other.id}].`;
const citations = validateCitations(text, documentFile, documentFile.blocks).citations;
const session = {isBusy:false,isGenerating:false,messages:[],currentDoc:documentFile,redoResponse:()=>{}};
question.state = answer.state = {chatSession:session};
question.message = {role:'user',text:'Why should a new key pair be used for each transaction? Cite the paper.',senderName:'User'};
answer.message = {role:'assistant',text,citations,senderName:'Gemma 4 E4B',readingScope:'Full readable text',state:'complete'};
answer.addEventListener('source-selected', (event:any)=>viewer.revealSource(event.detail.id));
await answer.updateComplete;
await viewer.updateComplete;
await viewer.revealSource(source.id);
